name = "portfolio"
build.watch_dir = ["app", "public", "functions"]
compatibility_date = "2025-11-17"
build.command = "bun run build:remix"
pages_build_output_dir = "build/client"

[vars]
NODE_ENV = "production"
VITE_BASE_URL = "https://ageha734.jp"
VITE_GOOGLE_ANALYTICS_ENABLED = true
VITE_GOOGLE_TAG_MANAGER_ENABLED = true
VITE_XSTATE_INSPECTOR_ENABLED = false
VITE_SENTRY_ENVIRONMENT = "production"
VITE_SENTRY_TRACES_SAMPLE_RATE = "1"
VITE_SENTRY_REPLAY_SAMPLE_RATE = "0"
VITE_SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE = "0"

[env.preview.vars]
NODE_ENV = "development"
VITE_BASE_URL = "https://dev.ageha734.jp"
VITE_GOOGLE_ANALYTICS_ENABLED = false
VITE_GOOGLE_TAG_MANAGER_ENABLED = false
VITE_XSTATE_INSPECTOR_ENABLED = true
VITE_SENTRY_ENVIRONMENT = "development"
VITE_SENTRY_TRACES_SAMPLE_RATE = "1"
VITE_SENTRY_REPLAY_SAMPLE_RATE = "0"
VITE_SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE = "0"
